services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=root
      - RABBITMQ_PASS=root
      - HEALTH_CHECK_CACHE=0
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chat=box