app:
  message: Message has been sent successfully!
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    exchange: user.exchange
    routingkey: user.queue
  jwt:
    expiration: 1800000
    secret: 123
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat-box